"""adding table with change1

Revision ID: 59df480dd51f
Revises: c8c0981ce055
Create Date: 2022-01-25 18:51:11.162879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59df480dd51f'
down_revision = 'c8c0981ce055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('author', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
